service: greps-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    ADMIN_EMAIL: ${env:ADMIN_EMAIL}
    ADMIN_PASSWORD: ${env:ADMIN_PASSWORD}
    BREVO_API_KEY: ${env:BREVO_API_KEY}
    BREVO_USER: ${env:BREVO_USER}
    BREVO_PASS: ${env:BREVO_PASS}

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY

package:
  excludeDevDependencies: true
  patterns:
    - '!node_modules/.cache/**'
    - '!queue*/**'
    - '!.git/**'
    - '!.env'