service: greps-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

  environment:
    MONGO_URI: ${env:MONGO_URI}

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /{any+}
          method: ANY

package:
  patterns:
    - '!.git/**'
    - '!.env'

plugins:
  - serverless-offline