name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Serverless
      run: npm install -g serverless

    - name: Install dependencies
      run: |
        cd Backend
        npm install

    - name: Deploy
      run: |
        cd Backend
        serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: ap-south-1